name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          skip-publish: false
