name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ github.token }}
          deploy-branch: gh-pages
          skip-publish: false
